version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=mongodb+srv://mkaifm728_db_user:Kaifyyy@cluster0.vtme9pp.mongodb.net/unnatisetu?retryWrites=true&w=majority
      - JWT_SECRET=sih_2026_mota_tribal_affairs_secret_key_jwt_super_secure
    volumes:
      - ./backend/prisma:/app/prisma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
    depends_on:
      - backend
